apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: gobuy
build:
  artifacts:
  - image: piotrostr/gobuy
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kube.yaml
